<a href="https://colab.research.google.com/github/kanishkdeep01/deep_learning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
print(device)

cuda


In [ ]:
numpy_array = np.array([[1.0,2.0],[3.0, 4.0]])

In [ ]:
pytorch_tensor = torch.tensor([[1.0,2.0],[3.0,4.0]])

In [ ]:
print(pytorch_tensor)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(numpy_array)

[[1. 2.]
 [3. 4.]]


In [ ]:
gpu_tensor = pytorch_tensor.to(device)

In [ ]:
print(gpu_tensor)

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')
