<a href="https://colab.research.google.com/github/kanishkdeep01/deep_learning/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [15]:
tensor_1  = torch.tensor([1.0,2.0,3.0])

In [16]:
tensor_2 = torch.zeros(2,3)

In [17]:
print(tensor_2)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [18]:
tensor_2 = torch.zeros(2,2)

In [19]:
print(tensor_2)

tensor([[0., 0.],
        [0., 0.]])


In [20]:
tensor_3 = torch.rand(3,3)

In [21]:
print(tensor_3)

tensor([[0.4812, 0.3330, 0.9838],
        [0.3456, 0.2441, 0.4192],
        [0.8669, 0.6979, 0.0051]])


In [22]:
result = tensor_2 + tensor_2

In [23]:
print(tensor_2)

tensor([[0., 0.],
        [0., 0.]])


In [24]:
result1 = torch.matmul(tensor_1,tensor_3)

In [25]:
print(result1)

tensor([3.7731, 2.9150, 1.8374])


In [1]:
x = torch.tensor(3.0,requires_grada = True)

NameError: name 'torch' is not defined